Add method to get User/Channel ID
pipozzz/rocket-python pull request #49
Opened 2020-06-16 12:53 UTC by soundstorm

Allow call to get ID of public room (channel) or user; bump to 1.2.15
Will allow better code for https://github.com/fraschetti/Octoslack/pull/93

2020-06-16 12:57 UTC, soundstorm commented
Although the call of `get_room_id` (and `set_room_topic` too) to acquire the id of a group instead of a channel is misleading, as `get_room_history` is a call on channels, but would be a breaking change otherwise.
Maybe this could be a cleanup for further releases?
Or add an alias for them like `get_private_room_id`, `set_private_room_topic`, `get_public_room_history` and deprecate the others.

2020-07-04 11:31 UTC, soundstorm commented
Hey @pipozzz can you have a look? Closed most of your open issues and made a few enhancements.

2020-07-17 11:40 UTC, pipozzz commented
I'm a little busy right now, but definitely I'll review it and let you know. Thanks for contribution.

2020-07-17 11:49 UTC, pipozzz requested changes

2020-07-17 11:49 UTC, pipozzz commented on setup.py
> +      version='1.2.15',
Please do not touch version numbers, I update it automatically wen I'm doing releases.
```suggestion
      version='1.2.14',
```

2020-07-17 11:49 UTC, pipozzz commented on .bumpversion.cfg
> +current_version = 1.2.15
Please do not touch version numbers, I update it automatically wen I'm doing releases.
```suggestion
current_version = 1.2.14
```

2020-08-17 09:01 UTC, pipozzz requested changes

2020-08-17 09:22 UTC, pipozzz commented
Also we need to resolve failed build before merging, btw Thanks for your contribution again ! 👍

2020-11-10 19:49 UTC, GrabsOrion commented
Hello, @soundstorm! 
Are you planning to fix the failed build?
As much as I know, the message from Travis CI not so crucial: 
> 'rocketchat.calls.groups.upload_remote_file.UploadRemoteFile' imported but unused

I'm very new to programming, but interested in the project, thank you!

2021-03-11 08:11 UTC, pipozzz commented
It seems that code is OK just test coverage dropped below 85%.

2022-03-03 12:32 UTC, merged

2024-02-28 11:16 UTC, soundstorm commented
This is still in the refresh branch after two years, will there be a release with those changes anytime?

2024-02-29 13:55 UTC, pipozzz commented
Hi @soundstorm, I was very busy, but Yes I'll review it and merge it if it's fine. There was failed some test last time I took a look. So let me check it again and merge it if it's fine. Thanks